### ISSUE TITLE
ValueError: could not convert string to float: ''

### ISSUE THREAD

**Issue by radombb** [Kangarroar/diff-svc-GUI#3]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\diff-svc\DIFFSVCGUI.py", line 255, in <lambda>
    self.start_rendering = ttk.Button(self.TNotebook1_t3, command=lambda: render(self, file_path, svc_model))
  File "D:\diff-svc\DIFFSVCGUI.py", line 65, in render
    formant_shift_ratio = float(formant_shift_ratio_str)
ValueError: could not convert string to float: ''

whlie rendering this error message show up in the last,the converted audio still show up though.The audio sounds legit ,not sure whether this error affect the result.

**Comment by Kangarroar** [comment]
Seems like you wanted to use the gender flag, gender flag works like this:
1.0 is default
1.05 is g+5 for a more female tone
0.95 is g-5 for a more male tone
